# Generated by Django 5.2.14 on 2026-10-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(help_text="e.g., '01', 'Table 05'", max_length=20, unique=True)),
                ('table_name', models.CharField(blank=True, help_text="Descriptive name, e.g., 'Corner Garden Booth'", max_length=100)),
                ('qr_token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Number of seats')),
                ('location', models.CharField(choices=[('Main Hall', 'Main Hall'), ('Window Side', 'Window Side'), ('Terrace Garden', 'Terrace Garden'), ('Private Lounge', 'Private Lounge'), ('Outdoor Patio', 'Outdoor Patio')], default='Main Hall', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Active tables are available for QR ordering and reservations')),
                ('qr_image', models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cafe Table',
                'verbose_name_plural': 'Cafe Tables',
                'ordering': ['table_number'],
            },
        ),
    ]
