# Generated by Django 5.2.18 on 2026-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(default='Artisan Brew Cafe', max_length=150)),
                ('tagline', models.CharField(default='Crafted Coffee & Cozy Moments', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cafe/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='cafe/favicons/')),
                ('short_description', models.TextField(default='Your local artisanal coffee haven offering hand-brewed specialty coffee, freshly baked pastries, and a warm, welcoming atmosphere.')),
                ('about_description', models.TextField(default='Founded with a passion for exceptional coffee and heartfelt hospitality, Artisan Brew Cafe brings people together over single-origin roasts and mouth-watering bites. Every bean is carefully sourced, expertly roasted, and brewed with precision.')),
                ('phone', models.CharField(default='+91 81608 51350', max_length=25)),
                ('email', models.EmailField(default='hello@artisancafe.com', max_length=254)),
                ('address', models.CharField(default='124 Coffee Lane, Brigade Road, Bangalore, Karnataka 560001', max_length=255)),
                ('google_maps_url', models.TextField(blank=True, default='https://maps.google.com/?q=Brigade+Road+Bangalore')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('whatsapp_number', models.CharField(blank=True, default='+917405401350', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cafe Setting',
                'verbose_name_plural': 'Cafe Settings',
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('opening_time', models.CharField(default='08:00 AM', max_length=30)),
                ('closing_time', models.CharField(default='10:00 PM', max_length=30)),
                ('is_closed', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opening Hour',
                'verbose_name_plural': 'Opening Hours',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
