# Generated by Django 5.2.14 on 2026-10-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafesetting',
            name='about_description',
            field=models.TextField(default='Founded with a passion for soulful coffee and heartfelt hospitality, Mitra Cafe brings friends and families together over rich brews and authentic flavors.'),
        ),
        migrations.AlterField(
            model_name='cafesetting',
            name='address',
            field=models.CharField(default='Mitra Cafe, Chhaprabhatha, Surat, Gujarat 394520', max_length=255),
        ),
        migrations.AlterField(
            model_name='cafesetting',
            name='cafe_name',
            field=models.CharField(default='Mitra Cafe', max_length=150),
        ),
        migrations.AlterField(
            model_name='cafesetting',
            name='email',
            field=models.EmailField(default='jenildiyora760@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='cafesetting',
            name='google_maps_url',
            field=models.TextField(blank=True, default='https://maps.app.goo.gl/YjiYuT8wt5XhwfJC7'),
        ),
        migrations.AlterField(
            model_name='cafesetting',
            name='phone',
            field=models.CharField(default='+91 7405401350', max_length=25),
        ),
        migrations.AlterField(
            model_name='cafesetting',
            name='short_description',
            field=models.TextField(default='Your beloved neighborhood cafe offering handcrafted specialty coffees, freshly baked delicacies, and a warm, vibrant atmosphere.'),
        ),
        migrations.AlterField(
            model_name='cafesetting',
            name='tagline',
            field=models.CharField(default='Crafted Coffee, Delicious Bites & Warm Moments', max_length=255),
        ),
    ]
